#!/usr/bin/env python3
"""
CWIC companies (MNC): build + check.

  companies.csv   one row per company: key, name, sector, invite_event
  templates.txt   the per-company HoI4 script, written once per sector
  Run:            python _tools/companies/build_companies.py
  It (re)writes:  common/scripted_effects/CWIC_MNC_Generated_Effects.txt

Adding a company: add a row to companies.csv (key in lower_snake_case, sector one of
hydrocarbons / mining / agri / manufacturing / electronics, a free CWIC_MNC.1xxx invite event),
add its loc / decisions / events as before, then run this script.
Changing how every company of a sector behaves: edit the matching #@each block in templates.txt.

Template syntax:
  #@each sector=<sector> ... #@end   repeat for every company of that sector (csv order)
  #@each all ... #@end               repeat for every company
  <corp> <Name> <sector> <invite_event>   placeholders
"""
import csv, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(os.path.dirname(HERE))
OUTPUTS = [  # (template, generated file)
    ("templates.txt", os.path.join(MOD, "common/scripted_effects/CWIC_MNC_Generated_Effects.txt")),
    ("templates_ideas.txt", os.path.join(MOD, "common/ideas/CWIC_Company_Ideas_Generated.txt")),
]
OUT_LOC = os.path.join(MOD, "localisation/english/CWIC_Company_Ideas_l_english.yml")
SECTOR_NAMES = {"hydrocarbons": "Oil", "mining": "Mining", "agri": "Agriculture", "manufacturing": "Manufacturing", "electronics": "Electronics"}
SECTORS = ("hydrocarbons", "mining", "agri", "manufacturing", "electronics")


def load():
    with open(os.path.join(HERE, "companies.csv"), encoding="utf-8-sig", newline="") as fh:
        rows = [{k: (v or "").strip() for k, v in r.items()} for r in csv.DictReader(fh)]
    errors = []
    keys, events = set(), set()
    for r in rows:
        if not re.fullmatch(r"\w+", r["key"]) or r["key"] != r["key"].lower(): errors.append("%s: key must be lower_snake_case" % r["key"])
        if r["key"] in keys: errors.append("%s: duplicate key" % r["key"])
        if r["sector"] not in SECTORS: errors.append("%s: unknown sector '%s'" % (r["key"], r["sector"]))
        if r["invite_event"] in events: errors.append("%s: invite_event %s already used" % (r["key"], r["invite_event"]))
        keys.add(r["key"]); events.add(r["invite_event"])
    return rows, errors


def expand(template, rows):
    out, block, sel = [], None, None
    for line in template.split("\n"):
        m = re.match(r"#@each (?:sector=(\w+)|all)\s*$", line)
        if m:
            block, sel = [], m.group(1)
            continue
        if line.strip() == "#@end":
            body = "\n".join(block)
            for r in rows:
                if sel is None or r["sector"] == sel:
                    out.append(body.replace("<corp>", r["key"]).replace("<Name>", r["name"])
                               .replace("<sector>", r["sector"]).replace("<invite_event>", r["invite_event"]))
            block = None
            continue
        (block if block is not None else out).append(line)
    if block is not None:
        raise SystemExit("templates.txt: #@each without #@end")
    return "\n".join(out)


def main():
    rows, errors = load()
    for e in errors:
        print("ERROR:", e)
    if errors:
        sys.exit(1)
    for tname, out in OUTPUTS:
        text = "# GENERATED by _tools/companies/build_companies.py from companies.csv + %s - do not edit by hand.\n\n" % tname
        text += expand(open(os.path.join(HERE, tname), encoding="utf-8").read(), rows)
        with open(out, "w", encoding="utf-8", newline="\r\n") as fh:
            fh.write(text)
    # politics-screen text for the foreign investment slots and company ideas
    loc = ["l_english:", ' foreign_investment: "Foreign Investment"']
    for sec, nm in SECTOR_NAMES.items():
        loc.append(' cwic_fi_%s: "%s Partner"' % (sec, nm))
    for r in rows:
        sec = SECTOR_NAMES[r["sector"]].lower()
        loc.append(' cwic_fi_%s: "%s"' % (r["key"], r["name"]))
        loc.append(' cwic_fi_%s_desc: "Invite §Y%s§! to invest in our %s sector (60 months, 90 day cooldown)."' % (r["key"], r["name"], sec))
        loc.append(' cwic_fi_%s_concession: "%s (Concession)"' % (r["key"], r["name"]))
        loc.append(' cwic_fi_%s_concession_desc: "Grant §Y%s§! a concession in our %s sector (84 months, 180 day cooldown)."' % (r["key"], r["name"], sec))
    with open(OUT_LOC, "w", encoding="utf-8-sig", newline="\r\n") as fh:
        fh.write("\n".join(loc) + "\n")
    per_sector = {s: sum(r["sector"] == s for r in rows) for s in SECTORS}
    print("%d companies built %s" % (len(rows), per_sector))


if __name__ == "__main__":
    main()
