#!/usr/bin/env python3
"""
CWIC super events: build + check.

  super_events.csv  is the only file you edit. One row per super event.
  Run:              python _tools/super_events/build_super_events.py
  It (re)writes:    common/scripted_effects/CWIC_Super_Event_Generated_Effects.txt
                    common/scripted_localisation/CWIC_Super_Event_Generated_Loc.txt
                    interface/CWIC_Super_Event_Generated.gfx
  and checks every row (sprite, loc keys, songs, duplicates). It exits with an error
  if something is broken, so nothing ships with a blank popup.

Adding a super event:
  1. Put the picture in gfx/super_event/ (e.g. My_Event.png).
  2. Add title/option/quote lines to localisation/english/CWIC_Super_Events_l_english.yml.
  3. Add a row to super_events.csv (next free id). Columns:
       id        unique number, never reuse or renumber (saved games store it)
       effect    name of the fire effect to generate, e.g. Super_Event_My_Event_Play
       window    popup (default) | korea | japan
       picture   GFX sprite name, or a file name in gfx/super_event/ (sprite is generated)
       title / option / quote   localisation keys (option may be empty -> generic "Continue")
       song      play_song name (optional)      sound   sound_effect name (optional)
       variants  per-country overrides: "quote@SOV=KEY; title@USA=KEY; song@FRA=SONG"
       once      yes = each player sees it at most once
       notes     free text
  4. Run this script. 5. Fire it from any event/focus/decision:  Super_Event_My_Event_Play = yes
"""
import csv, glob, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(os.path.dirname(HERE))
OUT_EFFECTS = os.path.join(MOD, "common/scripted_effects/CWIC_Super_Event_Generated_Effects.txt")
OUT_LOC = os.path.join(MOD, "common/scripted_localisation/CWIC_Super_Event_Generated_Loc.txt")
OUT_GFX = os.path.join(MOD, "interface/CWIC_Super_Event_Generated.gfx")
HEADER = "# GENERATED by _tools/super_events/build_super_events.py from super_events.csv - do not edit by hand.\n\n"
WINDOW_FLAGS = {"popup": "CWIC_Super_Event_Visible", "korea": "KOR_Big_Event_Flag", "japan": "JAP_Big_Event_Flag"}
FIELDS = ("picture", "title", "option", "quote", "song")


def read(p):
    return open(p, encoding="utf-8-sig", errors="replace").read()


def load_rows():
    rows = []
    with open(os.path.join(HERE, "super_events.csv"), encoding="utf-8-sig", newline="") as fh:
        for r in csv.DictReader(fh):
            r = {k: (v or "").strip() for k, v in r.items()}
            r["id"] = int(r["id"])
            r["window"] = r["window"] or "popup"
            r["variants"] = [v.strip() for v in r["variants"].split(";") if v.strip()]
            rows.append(r)
    return rows


def parse_variant(v):
    m = re.fullmatch(r"(\w+)@(\w+)=(\S+)", v)
    if not m or m.group(1) not in FIELDS:
        raise ValueError(v)
    return m.groups()  # field, tag, value


def picture_sprite(r):
    p = r["picture"]
    return p if p.startswith("GFX_") or not p else "GFX_CWIC_super_event_%d" % r["id"]


def check(rows):
    errors, warnings = [], []
    sprites, songs, loc = set(), set(), set()
    for p in glob.glob(os.path.join(MOD, "interface/**/*.gfx"), recursive=True):
        sprites |= set(re.findall(r'name\s*=\s*"(GFX_[^"]+)"', read(p)))
    for p in glob.glob(os.path.join(MOD, "music/**/*.asset"), recursive=True) + glob.glob(os.path.join(MOD, "sound/**/*.asset"), recursive=True):
        songs |= set(re.findall(r'name\s*=\s*"?([\w.]+)', read(p)))
    for p in glob.glob(os.path.join(MOD, "localisation/english/*.yml")):
        loc |= set(re.findall(r'^\s*([\w.\-]+):\d*\s*"', read(p), re.M))
    called = set()  # every "X = yes" in the mod's script, collected once
    for p in glob.glob(os.path.join(MOD, "common/**/*.txt"), recursive=True) + glob.glob(os.path.join(MOD, "events/*.txt")):
        if "CWIC_Super_Event_Generated" not in p:
            called |= set(re.findall(r"\b(\w+)\s*=\s*yes\b", read(p)))
    seen_id, seen_eff, unfired = {}, {}, []
    for r in rows:
        tag = "id %d (%s)" % (r["id"], r["effect"] or "no effect")
        if r["id"] in seen_id: errors.append("%s: duplicate id" % tag)
        if r["effect"] and r["effect"] in seen_eff: errors.append("%s: effect name also used by id %d" % (tag, seen_eff[r["effect"]]))
        seen_id[r["id"]] = 1; seen_eff[r["effect"]] = r["id"]
        if not r["effect"]: errors.append("%s: no effect name" % tag)
        if r["window"] not in WINDOW_FLAGS: errors.append("%s: unknown window '%s'" % (tag, r["window"]))
        pic = r["picture"]
        if not pic: errors.append("%s: no picture" % tag)
        elif pic.startswith("GFX_") and pic not in sprites: errors.append("%s: sprite %s does not exist" % (tag, pic))
        elif not pic.startswith("GFX_") and not os.path.exists(os.path.join(MOD, "gfx/super_event", pic)): errors.append("%s: gfx/super_event/%s not found" % (tag, pic))
        if not r["title"]: errors.append("%s: no title (also used by the Latest News list)" % tag)
        if r["window"] == "popup" and not r["quote"]: errors.append("%s: no quote" % tag)
        for fld in ("title", "option", "quote"):
            if r[fld] and r[fld] not in loc: errors.append("%s: %s key %s missing from english localisation" % (tag, fld, r[fld]))
        for v in r["variants"]:
            try:
                fld, _, val = parse_variant(v)
            except ValueError:
                errors.append("%s: bad variant '%s' (use field@TAG=VALUE)" % (tag, v)); continue
            if fld in ("title", "option", "quote") and val not in loc: errors.append("%s: variant key %s missing from english localisation" % (tag, val))
            if fld == "picture" and val not in sprites: errors.append("%s: variant sprite %s does not exist" % (tag, val))
        for s in [r["song"]] + [parse_variant(v)[2] for v in r["variants"] if v.startswith("song@")]:
            if s and songs and s not in songs: warnings.append("%s: song/sound %s not declared in music/ or sound/ (check spelling)" % (tag, s))
        if r["effect"] and r["effect"] not in called:
            unfired.append(r["id"])
    if unfired:
        warnings.append("%d super events are never fired (no '<effect> = yes' anywhere): ids %s" % (len(unfired), ", ".join(map(str, unfired))))
    return errors, warnings


def effects(rows):
    out = [HEADER]
    for r in rows:
        variants = [parse_variant(v) for v in r["variants"]]
        songs = [(t, v) for f, t, v in variants if f == "song"]
        limit = "is_ai = no" + (" NOT = { has_country_flag = CWIC_se_seen_%d }" % r["id"] if r["once"] == "yes" else "")
        body = ["%s = {  # super event %d" % (r["effect"], r["id"]),
                "\thidden_effect = {",
                "\t\tset_temp_variable = { CWIC_se_fire = %d }" % r["id"],
                "\t\tevery_country = {",
                "\t\t\tlimit = { %s }" % limit,
                "\t\t\tCWIC_Show_Super_Event = yes"]
        if r["once"] == "yes":
            body.append("\t\t\tset_country_flag = CWIC_se_seen_%d" % r["id"])
        sound = []
        if songs:
            for n, (t, s) in enumerate(songs):
                sound.append("\t\t\t\t%s = { limit = { tag = %s } play_song = \"%s\" }" % ("if" if n == 0 else "else_if", t, s))
            if r["song"]:
                sound.append("\t\t\t\telse = { play_song = \"%s\" }" % r["song"])
        elif r["song"]:
            sound.append("\t\t\t\tplay_song = \"%s\"" % r["song"])
        if r["sound"]:
            sound.append("\t\t\t\tsound_effect = \"%s\"" % r["sound"])
        if sound:  # only for players whose popup actually opened (respects their filter)
            body += ["\t\t\tif = {", "\t\t\t\tlimit = { check_variable = { CWIC_se_opened = 1 } }"] + sound + ["\t\t\t}"]
        body += ["\t\t}", "\t}", "}", ""]
        out.append("\n".join(body))
    # which window each id opens in
    out.append("# Opens the right window for CWIC_se_shown (called by CWIC_Show_Super_Event / CWIC_Reopen_SE_By_Id).")
    out.append("CWIC_Open_SE_Window = {")
    for f in WINDOW_FLAGS.values():
        out.append("\tclr_country_flag = %s" % f)
    branches = []
    for win in ("korea", "japan"):
        ids = [r["id"] for r in rows if r["window"] == win]
        if ids:
            cond = " ".join("check_variable = { CWIC_se_shown = %d }" % i for i in ids)
            branches.append("limit = { OR = { %s } } set_country_flag = %s" % (cond, WINDOW_FLAGS[win]))
    for n, b in enumerate(branches):
        out.append("\t%s = { %s }" % ("if" if n == 0 else "else_if", b))
    if branches:
        out.append("\telse = { set_country_flag = %s }" % WINDOW_FLAGS["popup"])
    else:
        out.append("\tset_country_flag = %s" % WINDOW_FLAGS["popup"])
    out.append("}\n")
    return "\n".join(out)


def loc_text(name, var, rows, field, fallback=None):
    lines = ["defined_text = {", "\tname = %s" % name]
    for r in rows:
        value = picture_sprite(r) if field == "picture" else r[field]
        for f, tag, v in (parse_variant(x) for x in r["variants"]):
            if f == field and var == "CWIC_se_shown":  # per-country variants only apply to the popup itself
                lines.append("\ttext = { trigger = { check_variable = { %s = %d } tag = %s } localization_key = %s }" % (var, r["id"], tag, v))
        if value:
            lines.append("\ttext = { trigger = { check_variable = { %s = %d } } localization_key = %s }" % (var, r["id"], value))
    if fallback:
        lines.append("\ttext = { localization_key = %s }" % fallback)
    lines.append("}\n")
    return "\n".join(lines)


def loc(rows):
    return HEADER + "\n".join([
        "# Popup windows (CWIC_se_shown = id of the super event on screen)",
        loc_text("get_superevent_texture", "CWIC_se_shown", rows, "picture"),
        loc_text("get_superevent_title", "CWIC_se_shown", rows, "title"),
        loc_text("get_superevent_option", "CWIC_se_shown", rows, "option", "CWIC_SUPER_EVENT_OPTION_DEFAULT"),
        loc_text("get_superevent_quote", "CWIC_se_shown", rows, "quote"),
        "# Latest News list (CWIC_se_view = id of the list entry)",
        loc_text("get_se_list_texture", "CWIC_se_view", rows, "picture"),
        loc_text("get_se_list_title", "CWIC_se_view", rows, "title"),
    ])


def gfx(rows):
    lines = [HEADER.replace("\n\n", "\n"), "spriteTypes = {"]
    for r in rows:
        if r["picture"] and not r["picture"].startswith("GFX_"):
            lines.append('\tspriteType = { name = "%s" texturefile = "gfx/super_event/%s" }' % (picture_sprite(r), r["picture"]))
    lines.append("}\n")
    return "\n".join(lines)


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(text)


def main():
    rows = sorted(load_rows(), key=lambda r: r["id"])
    errors, warnings = check(rows)
    for w in warnings:
        print("warning:", w)
    for e in errors:
        print("ERROR:", e)
    # Always write every row: skipping one would delete its fire effect and break its call sites.
    write(OUT_EFFECTS, effects(rows))
    write(OUT_LOC, loc(rows))
    write(OUT_GFX, gfx(rows))
    print("%d super events built, %d errors, %d warnings." % (len(rows), len(errors), len(warnings)))
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
