# Generates the USSR "State of the Union" dynamic modifier, slot effects, expiry events and loc.
# Usage: python gen.py <mod root>   (slot lists: slots.py; timed spirits + event ids: timed_ids.txt)
# Only regenerates the support files; call sites in focus/event files are edited by hand.
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from slots import POL, SEC, MIL, FOLD, CHAINS
from parse_ideas import parse, blocks

ROOT = sys.argv[1]
HERE = os.path.dirname(os.path.abspath(__file__))
TIMED = [l.split()[0] for l in open(os.path.join(HERE, 'timed_ids.txt')) if l.strip()]
NL = '\r\n'

defs = {}
for fn in os.listdir(os.path.join(ROOT, 'common/ideas')):
    if fn.endswith('.txt'):
        for idea, cat, body in parse(os.path.join(ROOT, 'common/ideas', fn)):
            defs[idea] = body

def kv(body):
    return re.findall(r'([\w\.]+)\s*=\s*([^\s{}]+)', body)

mods, techs = {}, {}
for n in FOLD:
    body = defs[n]
    m, t = {}, []
    for key, b, _, _ in blocks(body):
        if key == 'modifier':
            for k, v in kv(b):
                m[k.lower()] = m.get(k.lower(), 0) + float(v)
        elif key == 'research_bonus':
            t += [k for k, v in kv(b)]
        elif key in ('equipment_bonus', 'targeted_modifier', 'rule'):
            raise SystemExit(f'{n}: {key} cannot be folded')
    mods[n], techs[n] = m, t

keys = sorted({k for m in mods.values() for k in m})

def fmt(v):
    s = f'{v:.6f}'.rstrip('0').rstrip('.')
    return s if s not in ('-0', '') else '0'

T = '\t'
out = []
out.append('# Generated by the USSR spirit consolidation. Folds every non-chain Soviet spirit into one entry.')
out.append('SOV_state_of_the_union = {')
out.append(f'{T}icon = GFX_idea_gossnab')
out.append(f'{T}enable = {{ always = yes }}')
for k in keys:
    out.append(f'{T}{k} = SOV_sotu_{k}')
out.append('}')
dm = NL.join(out) + NL

E = []
E.append('# Generated by the USSR spirit consolidation.')
E.append('# The USSR holds at most one spirit per slot (political, security, military);')
E.append('# everything else is folded into the SOV_state_of_the_union dynamic modifier.')
E.append('')
for slot, members in (('political', POL), ('security', SEC), ('military', MIL)):
    E.append(f'SOV_clear_{slot}_spirit = {{')
    for n in members:
        E.append(f'{T}if = {{ limit = {{ has_idea = {n} }} remove_ideas = {n} }}')
    E.append('}')
E.append('')
E.append('SOV_sotu_ensure = {')
E.append(f'{T}if = {{')
E.append(f'{T}{T}limit = {{ NOT = {{ has_dynamic_modifier = {{ modifier = SOV_state_of_the_union }} }} }}')
E.append(f'{T}{T}add_dynamic_modifier = {{ modifier = SOV_state_of_the_union }}')
E.append(f'{T}}}')
E.append('}')
chain_of = {}
for c in CHAINS:
    for rank, alts in enumerate(c):
        for n in alts:
            others = [x for r in c for x in r if x != n]
            higher = [x for r in c[rank + 1:] for x in r]
            chain_of[n] = (others, higher)
ADD_E, SUB_E = [], []
for n in FOLD:
    m = mods[n]
    others, higher = chain_of.get(n, ([], []))
    E_ = ADD_E
    E_.append('')
    E_.append(f'SOV_sotu_add_{n} = {{')
    E_.append(f'{T}if = {{')
    blockers = ' '.join(f'has_country_flag = SOV_sotu_{x}' for x in [n] + higher)
    E_.append(f'{T}{T}limit = {{ NOT = {{ OR = {{ {blockers} }} }} }}')
    for x in others:
        E_.append(f'{T}{T}SOV_sotu_sub_{x} = yes')
    E_.append(f'{T}{T}custom_effect_tooltip = SOV_sotu_add_tt')
    E_.append(f'{T}{T}show_ideas_tooltip = {n}')
    for c in techs[n]:
        E_.append(f'{T}{T}add_tech_bonus = {{ name = {n} bonus = 0.5 uses = 1 category = {c} }}')
    E_.append(f'{T}{T}hidden_effect = {{')
    E_.append(f'{T}{T}{T}set_country_flag = SOV_sotu_{n}')
    E_.append(f'{T}{T}{T}SOV_sotu_ensure = yes')
    for k, v in m.items():
        E_.append(f'{T}{T}{T}add_to_variable = {{ SOV_sotu_{k} = {fmt(v)} }}')
    E_.append(f'{T}{T}{T}force_update_dynamic_modifier = yes')
    E_.append(f'{T}{T}}}')
    E_.append(f'{T}}}')
    E_.append('}')
    E_ = SUB_E
    E_.append('')
    E_.append(f'SOV_sotu_sub_{n} = {{')
    E_.append(f'{T}if = {{')
    E_.append(f'{T}{T}limit = {{ has_country_flag = SOV_sotu_{n} }}')
    E_.append(f'{T}{T}custom_effect_tooltip = SOV_sotu_sub_tt')
    E_.append(f'{T}{T}show_ideas_tooltip = {n}')
    E_.append(f'{T}{T}hidden_effect = {{')
    E_.append(f'{T}{T}{T}clr_country_flag = SOV_sotu_{n}')
    for k, v in m.items():
        E_.append(f'{T}{T}{T}add_to_variable = {{ SOV_sotu_{k} = {fmt(-v)} }}')
    E_.append(f'{T}{T}{T}force_update_dynamic_modifier = yes')
    E_.append(f'{T}{T}}}')
    E_.append(f'{T}}}')
    E_.append('}')
E += ['', '# --- remove effects (defined first: the add effects call them) ---'] + SUB_E + ['', '# --- add effects ---'] + ADD_E
eff = NL.join(E) + NL

V = ['add_namespace = SOV_sotu', '', '# Generated: expiry of timed spirits folded into SOV_state_of_the_union.',
     '# Fires after the original duration; skipped if the spirit was refreshed (end date moved).']
for i, n in enumerate(TIMED, 1):
    V += ['', 'country_event = {', f'{T}id = SOV_sotu.{i}', f'{T}hidden = yes', f'{T}is_triggered_only = yes',
          f'{T}immediate = {{', f'{T}{T}if = {{',
          f'{T}{T}{T}limit = {{',
          f'{T}{T}{T}{T}has_country_flag = SOV_sotu_{n}',
          f'{T}{T}{T}{T}check_variable = {{ var = global.num_days value = SOV_sotu_end_{n} compare = greater_than_or_equals }}',
          f'{T}{T}{T}}}',
          f'{T}{T}{T}SOV_sotu_sub_{n} = yes',
          f'{T}{T}}}', f'{T}}}', '}']
ev = NL.join(V) + NL

L = ['l_english:',
     ' SOV_state_of_the_union:0 "State of the Union"',
     ' SOV_state_of_the_union_desc:0 "The sum of the Union\'s economic plans, social campaigns and institutional reforms. Policies that once stood as separate national spirits now feed into this single assessment of the Soviet state."',
     ' SOV_sotu_add_tt:0 "§YState of the Union§! gains the effects of:"',
     ' SOV_sotu_sub_tt:0 "§YState of the Union§! loses the effects of:"']
loc = '﻿' + '\n'.join(L) + '\n'

def w(path, text):
    p = os.path.join(ROOT, path)
    with open(p, 'w', encoding='utf-8', newline='') as f:
        f.write(text)
w('common/dynamic_modifiers/SOV_state_of_the_union.txt', dm)
w('common/scripted_effects/SOV_spirit_slots.txt', eff)
w('events/SOV_state_of_the_union.txt', ev)
w('localisation/english/SOV_state_of_the_union_l_english.yml', loc)
print('keys', len(keys), 'fold', len(FOLD), 'timed events', len(TIMED))
print('tech bonuses:', {n: t for n, t in techs.items() if t})
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'timed_ids.txt'), 'w') as f:
    f.write('\n'.join(f'{n} SOV_sotu.{i}' for i, n in enumerate(TIMED, 1)))
