#!/usr/bin/env python3
"""
CWIC religions: build.

  religions.csv  one row per religion, in tie-break order:
                   variable   state variable holding its share (e.g. ReligionIslamSunni)
                   flag_name  suffix of the Religion_Minority_<N>_<flag_name> state flags
                   map_color  "r g b" (0-255) used by the religion map mode
  Run:           python _tools/religions/build_religions.py  (or _tools/build_all.py)
  It (re)writes: common/scripted_effects/CWIC_Religion_Generated_Effects.txt
                 common/scripted_triggers/CWIC_Religion_Generated_Triggers.txt

Adding a religion: add a row, give states a value for its variable in history, add its loc/icon, run this.
"""
import csv, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(os.path.dirname(HERE))
OUT_EFFECTS = os.path.join(MOD, "common/scripted_effects/CWIC_Religion_Generated_Effects.txt")
OUT_TRIGGERS = os.path.join(MOD, "common/scripted_triggers/CWIC_Religion_Generated_Triggers.txt")
HEADER = "# GENERATED by _tools/religions/build_religions.py from religions.csv - do not edit by hand.\n\n"
RANKS = 4


def load():
    with open(os.path.join(HERE, "religions.csv"), encoding="utf-8-sig", newline="") as fh:
        rows = [{k: (v or "").strip() for k, v in r.items()} for r in csv.DictReader(fh)]
    errors, seen = [], set()
    for r in rows:
        if not re.fullmatch(r"\w+", r["variable"]) or not re.fullmatch(r"\w+", r["flag_name"]):
            errors.append("%s: variable/flag_name must be single words" % r["variable"])
        if r["variable"] in seen:
            errors.append("%s: duplicate" % r["variable"])
        seen.add(r["variable"])
        if len(r["map_color"].split()) != 3:
            errors.append("%s: map_color must be 'r g b'" % r["variable"])
    return rows, errors


def effects(rows):
    v = [r["variable"] for r in rows]
    out = [HEADER]
    out.append("backup_religion_variables = {\n" + "".join("\tset_variable = { %s_backup = %s }\n" % (x, x) for x in v) + "}\n")
    out.append("restore_religion_variables = {\n" + "".join("\tset_variable = { %s = %s_backup }\n" % (x, x) for x in v) + "}\n")
    # STATE scope, called after the majority religion's variable has been set to 0.
    # For each rank 1-4: if every religion is 0 -> Religion_Minority_<N>_Null, otherwise the largest
    # remaining religion (ties: earliest in religions.csv) gets Religion_Minority_<N>_<flag_name> and is set to 0.
    body = ["cwic_religion_assign_minorities = {",
            "\t# Replaces the 120 get_<rank>_minority_in_<religion>_state effects (same result, same tie-breaking).",
            "\t# Input: temp var cwic_rel_majority = religions.csv index of the majority religion (already set to 0)."]
    all_zero = " ".join("check_variable = { %s = 0 }" % x for x in v)
    for n in range(1, RANKS + 1):
        body.append("\t# --- minority %d ---" % n)
        body.append("\tif = {")
        body.append("\t\tlimit = { %s }" % all_zero)
        body.append("\t\tset_state_flag = Religion_Minority_%d_Null" % n)
        body.append("\t}")
        body.append("\telse = {")
        body.append("\t\tset_temp_variable = { cwic_rel_best = 0 }")
        body.append("\t\tset_temp_variable = { cwic_rel_best_v = -1000000 }")
        for i, x in enumerate(v, start=1):  # strict > keeps the earliest religion on ties; the majority is skipped
            body.append("\t\tif = { limit = { NOT = { check_variable = { cwic_rel_majority = %d } } check_variable = { %s > cwic_rel_best_v } } set_temp_variable = { cwic_rel_best = %d } set_temp_variable = { cwic_rel_best_v = %s } }" % (i, x, i, x))
        for i, r in enumerate(rows, start=1):
            body.append("\t\t%s = { limit = { check_variable = { cwic_rel_best = %d } } set_state_flag = Religion_Minority_%d_%s set_variable = { %s = 0 } }"
                        % ("if" if i == 1 else "else_if", i, n, r["flag_name"], r["variable"]))
        body.append("\t}")
    body.append("}\n")
    out.append("\n".join(body))
    return "\n".join(out)


def tree(items, var, ind):
    # binary search over (index, r, g, b)
    if len(items) == 1:
        i, c = items[0]
        return "".join("%sset_temp_variable = { %s = %s }\n" % (ind, k, round(x / 255, 3)) for k, x in zip(("red", "green", "blue"), c))
    m = len(items) // 2
    return ("%sif = {\n%s\tlimit = { check_variable = { %s < %d } }\n" % (ind, ind, var, items[m][0]) + tree(items[:m], var, ind + "\t")
            + "%s}\n%selse = {\n" % (ind, ind) + tree(items[m:], var, ind + "\t") + "%s}\n" % ind)


def triggers(rows):
    out = [HEADER]
    top2 = ["# STATE scope. Finds the two largest religions: temp vars rel1/rel2 = index (1-%d, 0 = none), rel1_v/rel2_v = value." % len(rows),
            "cwic_state_religion_top2 = {"]
    top2 += ["\tset_temp_variable = { %s = 0 }" % x for x in ("rel1", "rel1_v", "rel2", "rel2_v")]
    for n, r in enumerate(rows, start=1):
        x = r["variable"]
        top2 += ["\tif = {",
                 "\t\tlimit = { check_variable = { %s > rel1_v } }" % x,
                 "\t\tset_temp_variable = { rel2 = rel1 }", "\t\tset_temp_variable = { rel2_v = rel1_v }",
                 "\t\tset_temp_variable = { rel1 = %d }" % n, "\t\tset_temp_variable = { rel1_v = %s }" % x,
                 "\t}", "\telse_if = {",
                 "\t\tlimit = { check_variable = { %s > rel2_v } }" % x,
                 "\t\tset_temp_variable = { rel2 = %d }" % n, "\t\tset_temp_variable = { rel2_v = %s }" % x, "\t}"]
    top2 += ["\talways = yes", "}", ""]
    out.append("\n".join(top2))
    colors = [(n, tuple(int(c) for c in r["map_color"].split())) for n, r in enumerate(rows, start=1)]
    out.append("# Input: temp var rid = religion index (religions.csv order). 0 -> dark grey (no data). Sets red/green/blue (0-1).\n"
               "cwic_religion_color = {\n\tset_temp_variable = { red = 0.235 }\n\tset_temp_variable = { green = 0.235 }\n\tset_temp_variable = { blue = 0.235 }\n"
               "\tif = {\n\t\tlimit = { check_variable = { rid > 0 } }\n" + tree(colors, "rid", "\t\t") + "\t}\n\talways = yes\n}\n")
    return "\n".join(out)


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(text)


def main():
    rows, errors = load()
    for e in errors:
        print("ERROR:", e)
    if errors:
        sys.exit(1)
    write(OUT_EFFECTS, effects(rows))
    write(OUT_TRIGGERS, triggers(rows))
    print("%d religions built" % len(rows))


if __name__ == "__main__":
    main()
