#!/usr/bin/env python3
"""
CWIC consumer goods trade: build.

  goods.csv       one row per tradeable consumer good:
                    key        variable form, e.g. cg_consumer_electronics_t1
                    name       effect-name form, e.g. cg_electronics_t1 (same as key except electronics)
                    cat / cat_snake / Cat / tier   name parts used by the variables
                    cut_event  trade.N event fired when the good is over-sold
                    price_key  suffix of the price_adjust_<price_key> array
  templates.txt   the per-good trade script, written once (#@each all ... #@end)
  Run:            python _tools/goods/build_goods.py  (or _tools/build_all.py)
  It (re)writes:  common/scripted_effects/CWIC_Goods_Generated_Effects.txt

Raw resources (oil, steel, ...) are NOT generated: they have legacy special cases and stay in
IC_Trade_Scripted_Effects.txt / IC_Trade_Scripted_Effects_Cuts.txt.
"""
import csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(MOD, "common/scripted_effects/CWIC_Goods_Generated_Effects.txt")


def placeholders(g):
    t = g["tier"]
    return {
        "<price_key>": g["price_key"], "<cut_event>": g["cut_event"],
        "<cg_snake_t>": "cg_%s_t%s" % (g["cat_snake"], t), "<cg_name_t>": "cg_%s_t%s" % (g["cat"], t),
        "<CgCatT>": "Cg%sT%s" % (g["Cat"], t), "<cgCatT>": "cg%sT%s" % (g["Cat"], t),
        "<cg_snake_>": "cg_%s_" % g["cat_snake"], "<cg_cat_>": "cg_%s_" % g["cat"],
        "<CatT>": "%sT%s" % (g["Cat"], t), "<_t>": "_t%s" % t,
    }


def main():
    with open(os.path.join(HERE, "goods.csv"), encoding="utf-8-sig", newline="") as fh:
        goods = [{k: (v or "").strip() for k, v in r.items()} for r in csv.DictReader(fh)]
    keys = [g["key"] for g in goods]
    dup = {k for k in keys if keys.count(k) > 1}
    if dup:
        sys.exit("ERROR: duplicate goods: %s" % sorted(dup))
    out, block = [], None
    for line in open(os.path.join(HERE, "templates.txt"), encoding="utf-8").read().split("\n"):
        if line.strip() == "#@each all":
            block = []
            continue
        if line.strip() == "#@end":
            body = "\n".join(block)
            for g in goods:
                text = body
                for k, v in placeholders(g).items():
                    text = text.replace(k, v)
                out.append(text)
            block = None
            continue
        (block if block is not None else out).append(line)
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("# GENERATED by _tools/goods/build_goods.py from goods.csv + templates.txt - do not edit by hand.\n\n" + "\n".join(out))
    print("%d consumer goods built" % len(goods))


if __name__ == "__main__":
    main()
