#!/usr/bin/env python3
"""Regenerate gfx/interface/equipmentdesigner/graphic_db/00_tank_icons.txt.

Art comes from the non-NSB technology sprite library (GFX_<TAG>_<legacy tech>_medium and the
generic GFX_<legacy tech>_medium). Each designer generation is matched to the legacy tier whose
equipment year is nearest the generation's year. Models already in the file are preserved.

    python3 "CWIC Backup/tools/build_designer_graphic_db.py" [--check]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MOD = ROOT / "Cold War Iron Curtain"
VANILLA = Path.home() / ".local/share/Steam/steamapps/common/Hearts of Iron IV"
TARGET = MOD / "gfx/interface/equipmentdesigner/graphic_db/00_tank_icons.txt"

HULL_YEARS = {
    "light": [1939, 1942, 1944, 1950, 1960, 1970, 1980, 1990, 2000, 2010],
    "medium": [1939, 1942, 1944, 1950, 1960, 1970, 1980, 1990, 2000, 2010],
    "heavy": [1939, 1942, 1944, 1950, 1955],
}

LIGHT_TANKS = [(f"light_tanks_{n}", y) for n, y in zip(range(1, 7), [1942, 1944, 1947, 1960, 1975, 1995])]
MAIN_BATTLE_TANKS = [("main_battle_tanks", 1942)] + [
    (f"main_battle_tanks_{n}", y)
    for n, y in zip(range(1, 10), [1944, 1947, 1950, 1960, 1965, 1975, 1985, 1995, 2005])
]
HEAVY_TANKS = [(f"heavy_tanks_{n}", y) for n, y in zip(range(1, 6), [1942, 1944, 1947, 1955, 1955])]
SPAAG = [(f"spaag_{n}", y) for n, y in zip(range(1, 6), [1940, 1955, 1970, 1985, 2000])]
LIGHT_SPG = [(f"light_sp_artillery_{n}", y) for n, y in zip(range(1, 6), [1945, 1960, 1975, 1990, 2005])]
MEDIUM_SPG = [(f"sp_artillery_{n}", y) for n, y in zip(range(1, 6), [1940, 1955, 1970, 1985, 2000])]
HEAVY_SPG = [(f"heavy_sp_artillery_{n}", y) for n, y in zip(range(1, 6), [1945, 1960, 1975, 1990, 2005])]
TANK_DESTROYER = [(f"tank_destroyer_{n}", y) for n, y in zip(range(1, 6), [1950, 1960, 1970, 1985, 1995])]
ATGM_CARRIER = [(f"atgm_carrier_{n}", y) for n, y in zip(range(0, 5), [1960, 1970, 1980, 1990, 2000])]
APC = [("mechanized_infantry", 1942)] + [
    (f"mechanized_infantry{n}", y)
    for n, y in zip(range(2, 11), [1944, 1947, 1950, 1960, 1965, 1975, 1985, 1995, 2005])
]
IFV = [("mechanized_heavy_infantry", 1947)] + [
    (f"mechanized_heavy_infantry{n}", y)
    for n, y in zip(range(2, 9), [1950, 1955, 1965, 1975, 1985, 1995, 2005])
]

ROLES = [
    ("light_tank_chassis", "light", LIGHT_TANKS),
    ("medium_tank_chassis", "medium", MAIN_BATTLE_TANKS),
    ("heavy_tank_chassis", "heavy", HEAVY_TANKS),
    ("light_tank_aa_chassis", "light", SPAAG),
    ("medium_tank_aa_chassis", "medium", SPAAG),
    ("light_tank_artillery_chassis", "light", LIGHT_SPG),
    ("medium_tank_artillery_chassis", "medium", MEDIUM_SPG),
    ("heavy_tank_artillery_chassis", "heavy", HEAVY_SPG),
    ("light_tank_destroyer_chassis", "light", TANK_DESTROYER[:1] + ATGM_CARRIER),
    ("medium_tank_destroyer_chassis", "medium", TANK_DESTROYER),
    ("heavy_tank_destroyer_chassis", "heavy", TANK_DESTROYER),
    ("light_tank_apc_chassis", "light", APC),
    ("medium_tank_apc_chassis", "medium", APC),
    ("light_tank_ifv_chassis", "light", IFV),
    ("medium_tank_ifv_chassis", "medium", IFV),
]

COUNTRY_TOLERANCE = 10
ALTERNATE_WEIGHT = 0.5

HEADER = """\
# Cold War Iron Curtain tank designer graphic database.
# Generated by CWIC Backup/tools/build_designer_graphic_db.py - edit the tool, not this file.
#
# Keyed on the exact per-generation equipment type. The first pool is the Equipment Match: the
# non-NSB technology art whose legacy equipment year is nearest the generation's year. The
# weight 0.5 pool offers the rest of that role family's art as selectable alternates.
# "default" carries the generic art, so a country without its own art for a role still gets
# that role's picture instead of falling through to the plain tank hull.
"""


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def registered_sprites() -> set[str]:
    sprites = set()
    for path in sorted((MOD / "interface").rglob("*.gfx")):
        body = read(path)
        for block in re.finditer(r"spriteType\s*=\s*\{(.*?)\}", body, re.S | re.I):
            name = re.search(r'name\s*=\s*"(GFX_[A-Za-z0-9_]+)"', block.group(1))
            texture = re.search(r'texturefile\s*=\s*"([^"]+)"', block.group(1), re.I)
            if not name or not texture:
                continue
            relative = texture.group(1).replace("\\", "/")
            if (MOD / relative).is_file() or (VANILLA / relative).is_file():
                sprites.add(name.group(1))
    return sprites


def existing_models() -> dict[tuple[str, str], list[str]]:
    models: dict[tuple[str, str], list[str]] = {}
    if not TARGET.exists():
        return models
    tag = None
    key = None
    in_models = False
    for line in read(TARGET).splitlines():
        if m := re.match(r"^(\w+) = \{", line):
            tag = m.group(1)
        elif m := re.match(r"^\t(\w+) = \{", line):
            key = m.group(1)
        elif re.match(r"^\t{3}models = \{", line):
            in_models = True
        elif in_models and re.match(r"^\t{3}\}", line):
            in_models = False
        elif in_models and (m := re.match(r"^\t{4}(\w+)", line)):
            models.setdefault((tag, key), []).append(m.group(1))
    return models


def nearest(tiers: list[tuple[str, int]], year: int) -> tuple[str, int]:
    return min(tiers, key=lambda tier: (abs(tier[1] - year), tier[1]))


def sprite(tag: str | None, tech: str) -> str:
    return f"GFX_{tag}_{tech}_medium" if tag else f"GFX_{tech}_medium"


def build() -> str:
    sprites = registered_sprites()
    models = existing_models()
    tags = sorted(
        {
            m.group(1)
            for name in sprites
            if (m := re.match(r"GFX_([A-Z][A-Z0-9]{2})_(\w+)_medium$", name))
            and any(m.group(2) == tech for _, _, tiers in ROLES for tech, _ in tiers)
        }
        | {tag for tag, _ in models}
    )

    out = [HEADER]
    for tag in [None] + tags:
        lines = []
        for role, hull, tiers in ROLES:
            owned = [tier for tier in tiers if sprite(tag, tier[0]) in sprites]
            for generation, year in enumerate(HULL_YEARS[hull]):
                key = f"{role}_{generation}"
                icons = []
                if owned:
                    target = nearest(tiers, year)
                    match = target if target in owned else nearest(owned, year)
                    if tag is None or abs(match[1] - year) <= COUNTRY_TOLERANCE or target in owned:
                        icons = [sprite(tag, match[0])]
                        icons += [sprite(tag, tech) for tech, _ in owned if tech != match[0]]
                pool_models = models.get((tag, key), []) if tag else []
                if not icons and not pool_models:
                    continue
                lines.append(f"\t{key} = {{")
                lines.append("\t\tpool = {")
                if icons:
                    lines += ["\t\t\ticons = {", f"\t\t\t\t{icons[0]}", "\t\t\t}"]
                if pool_models:
                    lines += ["\t\t\tmodels = {"] + [f"\t\t\t\t{m}" for m in pool_models] + ["\t\t\t}"]
                lines.append("\t\t}")
                if len(icons) > 1:
                    lines.append("\t\tpool = {")
                    lines.append(f"\t\t\tweight = {ALTERNATE_WEIGHT}")
                    lines += ["\t\t\ticons = {"] + [f"\t\t\t\t{i}" for i in reversed(icons[1:])] + ["\t\t\t}"]
                    lines.append("\t\t}")
                lines.append("\t}")
        if lines:
            out.append(f"{tag or 'default'} = {{")
            out += lines
            out.append("}")
            out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    body = build()
    if "--check" in sys.argv:
        current = TARGET.read_bytes().decode("utf-8") if TARGET.exists() else ""
        if current != body:
            print(f"{TARGET.relative_to(ROOT)} is stale; rerun without --check")
            sys.exit(1)
        print("designer graphic database is current")
    else:
        TARGET.write_bytes(body.encode("utf-8"))
        print(f"wrote {TARGET.relative_to(ROOT)}: {body.count('pool = {')} pools")
