#!/usr/bin/env python3
"""
CWIC cultures: build + check.

  cultures.csv   one row per culture:
                   id          number stored in the state array culture^n (never renumber: history files use it)
                   name        localisation key of the culture name
                   picture     GFX sprite shown for the majority culture
                   state_flag  state flag set while it is the majority culture
                   map_color   "r g b" (0-255) for the culture map mode
                 The description key is always CULTURAL_ID_DESCRIPTION_<id>_TT.
  Run:           python _tools/cultures/build_cultures.py  (or _tools/build_all.py)
  It (re)writes: common/scripted_localisation/CWIC_Culture_Generated_Loc.txt
                 common/scripted_effects/CWIC_Culture_Generated_Effects.txt
                 common/scripted_triggers/CWIC_Culture_Generated_Triggers.txt

Adding a culture: add a row with the next id, add its name/description loc and picture sprite,
use the id in history/states (add_to_array = { culture = <id> }), run this.
"""
import csv, glob, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(os.path.dirname(HERE))
OUT_LOC = os.path.join(MOD, "common/scripted_localisation/CWIC_Culture_Generated_Loc.txt")
OUT_EFF = os.path.join(MOD, "common/scripted_effects/CWIC_Culture_Generated_Effects.txt")
OUT_TRG = os.path.join(MOD, "common/scripted_triggers/CWIC_Culture_Generated_Triggers.txt")
HEADER = "# GENERATED by _tools/cultures/build_cultures.py from cultures.csv - do not edit by hand.\n\n"


def load():
    with open(os.path.join(HERE, "cultures.csv"), encoding="utf-8-sig", newline="") as fh:
        rows = [{k: (v or "").strip() for k, v in r.items()} for r in csv.DictReader(fh)]
    errors, warnings, ids = [], [], set()
    for r in rows:
        r["id"] = int(r["id"])
        if r["id"] in ids: errors.append("id %d: duplicate" % r["id"])
        ids.add(r["id"])
        if len(r["map_color"].split()) != 3: errors.append("id %d: map_color must be 'r g b'" % r["id"])
        for k in ("name", "picture", "state_flag"):
            if not r[k]: errors.append("id %d: no %s" % (r["id"], k))
    sprites, loc = set(), set()
    for p in glob.glob(os.path.join(MOD, "interface/**/*.gfx"), recursive=True):
        sprites |= set(re.findall(r'name\s*=\s*"(GFX_[^"]+)"', open(p, encoding="utf-8-sig", errors="replace").read()))
    for p in glob.glob(os.path.join(MOD, "localisation/english/*.yml")):
        loc |= set(re.findall(r'^\s*([\w.\-]+):\d*\s*"', open(p, encoding="utf-8-sig", errors="replace").read(), re.M))
    for r in rows:
        if r["picture"] not in sprites: warnings.append("id %d (%s): sprite %s not found" % (r["id"], r["name"], r["picture"]))
        if "CULTURAL_ID_DESCRIPTION_%d_TT" % r["id"] not in loc: warnings.append("id %d (%s): CULTURAL_ID_DESCRIPTION_%d_TT missing from english loc" % (r["id"], r["name"], r["id"]))
    return sorted(rows, key=lambda r: r["id"]), errors, warnings


def defined_text(name, slot, rows, value):
    lines = ["defined_text = {", "\tname = %s" % name]
    lines += ['\ttext = { trigger = { check_variable = { culture^%d = %d } } localization_key = %s }' % (slot, r["id"], value(r)) for r in rows]
    return "\n".join(lines + ["}", ""])


def loc(rows):
    name = lambda r: '"%s"' % r["name"]
    desc = lambda r: "CULTURAL_ID_DESCRIPTION_%d_TT" % r["id"]
    parts = [HEADER]
    for slot in range(4):
        parts.append(defined_text("get_number_%d_ethnic" % slot, slot, rows, name))
    for slot in range(1, 4):
        parts.append(defined_text("get_number_%d_ethnic_minority" % slot, slot, rows, desc))
    parts.append(defined_text("GetMajorityCulturalPic", 0, rows, lambda r: r["picture"]))
    parts.append(defined_text("GetMajorityCulturalDesc", 0, rows, desc))
    return "\n".join(parts)


def effects(rows):
    out = [HEADER, "# STATE scope. Clears every culture flag, then sets the one for the majority culture (culture^0).",
           "cwic_set_state_culture_flag = {"]
    out += ["\tclr_state_flag = %s" % r["state_flag"] for r in rows]
    for n, r in enumerate(rows):
        out.append("\t%s = { limit = { check_variable = { culture^0 = %d } } set_state_flag = %s }" % ("if" if n == 0 else "else_if", r["id"], r["state_flag"]))
    out.append("}\n")
    return "\n".join(out)


def tree(items, ind):
    if len(items) == 1:
        i, c, name = items[0]
        return "%s# %d - %s\n" % (ind, i, name) + "".join("%sset_temp_variable = { %s = %s }\n" % (ind, k, round(x / 255, 3)) for k, x in zip(("red", "green", "blue"), c))
    m = len(items) // 2
    return ("%sif = {\n%s\tlimit = { check_variable = { cid < %d } }\n" % (ind, ind, items[m][0]) + tree(items[:m], ind + "\t")
            + "%s}\n%selse = {\n" % (ind, ind) + tree(items[m:], ind + "\t") + "%s}\n" % ind)


def triggers(rows):
    items = [(r["id"], tuple(int(x) for x in r["map_color"].split()), r["name"]) for r in rows]
    return (HEADER + "# Culture map mode colour. Input: temp var cid = culture id. Unknown / 0 -> dark grey. Binary search, ~10 checks.\n"
            "cwic_culture_color = {\n\tset_temp_variable = { red = 0.235 }\n\tset_temp_variable = { green = 0.235 }\n\tset_temp_variable = { blue = 0.235 }\n"
            "\tif = {\n\t\tlimit = {\n\t\t\tcheck_variable = { cid > 0 }\n\t\t\tcheck_variable = { cid < %d }\n\t\t}\n" % (items[-1][0] + 1)
            + tree(items, "\t\t") + "\t}\n\talways = yes\n}\n")


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(text)


def main():
    rows, errors, warnings = load()
    for w in warnings: print("warning:", w)
    for e in errors: print("ERROR:", e)
    if errors: sys.exit(1)
    write(OUT_LOC, loc(rows)); write(OUT_EFF, effects(rows)); write(OUT_TRG, triggers(rows))
    print("%d cultures built, %d warnings" % (len(rows), len(warnings)))


if __name__ == "__main__":
    main()
